version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: jy@0Hyj3P1&r9&7ds9s
      MYSQL_DATABASE: oishiro
      MYSQL_USER: nemo
      MYSQL_PASSWORD: masterDatabaseForOishiroApp
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: